=== dqualizer/dqlang/schemas/api-schema/api-schema_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "API Schema",
  "properties": {
    "version": {
        "type": "integer",
        "description": "Version of this schema representation",
        "const": 1.0
    },
    "context": {
        "type": "string",
        "description": "The name of the Bounded Context to which this schema belongs",
        "minLength": 1
    },
    "api": {
      "type": "string",
      "description": "Used API Schema of the Bounded Context",
      "examples": ["OpenAPI_3.0.1", "GraphQL", "WSDL"],
      "minLength": 1
    },
    "server_info": {
      "type": "array",
      "description": "Collection of different URls of this Bounded Context",
      "uniqueItems": true,
        "items":  {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string",
                    "description": "URL of the host, also logical URLs",
                    "examples": ["localhost:8080", "10.10.110.1:5782", "https://aws.amazon.com/dqualizer-runtime-testing-tool/"]
                },
                "environment": {
                    "type": "string",
                    "description": "The environment this host belongs to",
                    "examples": ["PROD", "TEST", "INT", "QUAL"]
                }
            },
            "required": [
                "host",
                "environment"
            ]
        }   
    },
    "field": {
        "type": "array",
        "description": "Information about all endpoints of this Bounded Context",
        "uniqueItems": true,
        "patternProperties": {
            "items": {
                "type": "object",
                "description": "Information about one particular endpoint",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "Relative path of this endpoint"
                    },
                    "operation_id": {
                        "type": "string",
                        "description": "Name of this object inside the source code"
                    },
                    "operation": {
                        "type": "string",
                        "description": "Operation of this object",
                        "examples": ["GET", "POST", "QUERY", "MUTATION"]
                    },
                    "input": {
                        "type": "array",
                        "description": "Inputs like path variables or headers",
                        "uniqueItems": true,
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "in": {
                                    "type": "string",
                                    "description": "Location of the parameter",
                                    "examples": ["url", "header"]
                                },
                                "required": {
                                    "type": "boolean"
                                },
                                "type": {
                                    "type": "string",
                                    "examples": ["string", "integer"]
                                }
                            },
                            "required": [
                                "name",
                                "required",
                                "type"
                            ]
                        }
                    },
                    "body": {
                        "type": "object",
                        "patternProperties": {
                           ".*": {
                                "type": "object",
                                "description": "A specific content-type",
                                "examples": ["application/json", "application/xml"],
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "description": "Reference to the data schema of this body, see below for 'data_schema'"
                                    }
                                }
                            }
                        }
                    },
                    "output": {
                        "type": "array",
                        "description": "Relevant outputs like data types or status codes",
                        "uniqueItems": true,
                        "items": {
                            "type": "object",
                            "patternProperties": {
                                ".*": {
                                    "type": "object",
                                    "description": "A specific content-type",
                                    "examples": ["application/json", "application/xml"],
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "description": "Reference to the data schema of this body, see below for 'data_schema'"
                                        },
                                        "expected_code": {
                                            "type": "string"
                                        }
                                    },
                                    "required": ["type"]
                                }
                            } 
                        }   
                    }
                },
                "required": [
                    "operation_id",
                    "operation",
                    "input",
                    "body",
                    "output"
                ]
            }
        }   
    },
    "data_schemas": {
        "type": "object",
        "description": "Data schemas of all used data types in this API schema",
        "patternProperties": {
            ".*": {
                "type": "object",
                "description": "One particular data type",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "type description",
                        "examples": ["object", "long", "string", "date"]
                    }, 
                    "properties": {
                        "type": "array",
                        "description": "List of all data properties",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
  },
  "required": [
    "version",
    "context",
    "api",
    "server_info",
    "field",
    "data_schemas"
  ],
  "examples": [{
    "version": 1,
    "context": "werkstatt",
    "api": "OpenAPI_3.0.1",
    "field": [
      {
        "path": "/auftrag/new",
        "operation": "post",
        "input": [],
        "body": {
          "application/json": {
            "type": "Auftraggeber"
          }
        },
        "output": [
          {
            "application/json": {
              "type": "Werkstattauftrag",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "createAuftrag"
      },
      {
        "path": "/auftrag/{auftragsnummer}",
        "operation": "get",
        "input": [
          {
            "name": "auftragsnummer",
            "in": "path",
            "required": true,
            "type": "integer"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "Werkstattauftrag",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "readAuftrag"
      },
      {
        "path": "/auftrag/{auftragsnummer}",
        "operation": "put",
        "input": [
          {
            "name": "auftragsnummer",
            "in": "path",
            "required": true,
            "type": "integer"
          }
        ],
        "body": {
          "application/json": {
            "type": "Auftragsstatus"
          }
        },
        "output": [
          {
            "application/json": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "updateStatus"
      }
    ],
    "server_info": [
      {
        "host": "http://127.0.0.1:9000",
        "environment": "Generated server url"
      }
    ],
    "data_schemas": {
      "Werkstattauftrag": {
        "type": "object",
        "properties": [
          {
            "name": "auftraggeber",
            "type": "#/components/schemas/Auftraggeber"
          },
          {
            "name": "aktuellerBearbeiter",
            "type": "integer"
          },
          {
            "name": "werkstattauftragsnummer",
            "type": "integer"
          },
          {
            "name": "erstellungsdatum",
            "type": "string"
          },
          {
            "name": "zusaetzlicheMaterialien",
            "type": "array"
          },
          {
            "name": "werkstattauftragsstatus",
            "type": "string"
          },
          {
            "name": "auftragspositionen",
            "type": "array"
          },
          {
            "name": "auftraggeberHistorie",
            "type": "array"
          },
          {
            "name": "fahrzeugkennzeichen",
            "type": "string"
          },
          {
            "name": "bearbeiterverlauf",
            "type": "array"
          }
        ]
      },
      "Werkstattservice": {
        "type": "object",
        "properties": [
          {
            "name": "werkstattserviceRef",
            "type": "integer"
          },
          {
            "name": "materialien",
            "type": "array"
          },
          {
            "name": "bezeichnung",
            "type": "string"
          },
          {
            "name": "arbeitswert",
            "type": "#/components/schemas/Arbeitswert"
          }
        ]
      },
      "Auftragsposition": {
        "type": "object",
        "properties": [
          {
            "name": "auftragspositionsnummer",
            "type": "integer"
          },
          {
            "name": "werkstattservice",
            "type": "#/components/schemas/Werkstattservice"
          },
          {
            "name": "menge",
            "type": "number"
          }
        ]
      },
      "Material": {
        "type": "object",
        "properties": [
          {
            "name": "materialnummer",
            "type": "integer"
          },
          {
            "name": "bezeichnung",
            "type": "string"
          },
          {
            "name": "materialpreis",
            "type": "integer"
          },
          {
            "name": "menge",
            "type": "number"
          },
          {
            "name": "status",
            "type": "string"
          }
        ]
      },
      "Auftraggeber": {
        "type": "object",
        "properties": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "typ",
            "type": "string"
          },
          {
            "name": "id",
            "type": "integer"
          }
        ]
      },
      "Auftragsstatus": {
        "type": "object",
        "properties": [
          {
            "name": "status",
            "type": "string"
          }
        ]
      },
      "Arbeitswert": {
        "type": "object",
        "properties": [
          {
            "name": "geldwert",
            "type": "number"
          },
          {
            "name": "waehrung",
            "type": "string"
          },
          {
            "name": "menge",
            "type": "number"
          },
          {
            "name": "zeitwert",
            "type": "number"
          }
        ]
      }
    }
  },{
    "version": 1,
    "context": "sales",
    "api": "OpenAPI_3.0.1",
    "field": [
      {
        "path": "/riskmanagement/vote",
        "operation": "post",
        "input": [
          {
            "name": "contract_number",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "vote_result",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "voteContract"
      },
      {
        "path": "/riskmanagement/rating",
        "operation": "get",
        "input": [
          {
            "name": "contract_number",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "showCreditRating"
      },
      {
        "path": "/riskmanagement/contract",
        "operation": "get",
        "input": [
          {
            "name": "number",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "showContract"
      },
      {
        "path": "/riskmanagement/rate_contract",
        "operation": "post",
        "input": [
          {
            "name": "contract_number",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "creditRating",
            "in": "query",
            "required": true,
            "type": "integer"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "enterCreditRating"
      },
      {
        "path": "/sales/fillout_contract",
        "operation": "post",
        "input": [
          {
            "name": "contractNumber",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "lessee",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "car",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "price_amount",
            "in": "query",
            "required": true,
            "type": "integer"
          },
          {
            "name": "price_currency",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "filloutContract"
      },
      {
        "path": "/sales/sign_contract",
        "operation": "post",
        "input": [
          {
            "name": "contractNumber",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "signContract"
      },
      {
        "path": "/sales/view_contract",
        "operation": "get",
        "input": [
          {
            "name": "contractNumber",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "viewContract"
      },
      {
        "path": "/riskmanagement/contracts",
        "operation": "get",
        "input": [],
        "body": {},
        "output": [
          {
            "*/*": {
              "type": "string",
              "expected_code": "200"
            }
          }
        ],
        "operation_id": "listContracts"
      }
    ],
    "server_info": [
      {
        "host": "http://127.0.0.1:8080",
        "environment": "Generated server url"
      }
    ],
    "data_schemas": {}
  },{
    "version": 1.0,
    "context": "string",
    "api": "OpenAPI_3.0.1",
    "server_info": [
        {   
            "host": "localhost:8080",
            "environment": "TEST"
        }
    ],
    "field": [
        {
            "path": "/kinoapp/{version}/open",
            "operation_id": "openApp",
            "operation": "GET",
            "input": [
                {
                    "name": "version",
                    "in": "url",
                    "required": true,
                    "type": "long"
                }
            ],
            "body": {
                "application/json": {
                    "type": "Nutzer"
                },
                "application/xml": {
                    "type": "string"
                }
            },
            "output": [
                {
                    "application/json": {
                        "type": "string",
                        "expected_code": "200"
                    }
                },
                {
                    "application/json": {
                        "type": "string",
                        "expected_code": "404"
                    }
                }
            ]
        },
        {
            "path": "/graphql",
            "operation_id": "showAll",
            "operation": "Query",
            "input": [],
            "body": {},
            "output": [
                {
                    "application/json": {
                        "type": "string",
                        "expected_code": "200"
                    }
                }
            ]
        }
    ],
    "data_schemas": {
        "Nutzer": {
            "type": "object",
            "properties": [
               {
                    "name": "id",
                    "type": "long"
               },
               {
                    "name": "fullname",
                    "type": "string"
               },
               {
                    "name": "birthDate",
                    "type": "date"
                },
                {
                   "name": "custom",
                   "type": "#/data_schemas/Customclass"
                }
            ]
        },
        "Customclass": {}
    }
}]
}

=== dqualizer/dqlang/examples/api-schema/api-schema_autowerkstatt.json
{
  "version": 1,
  "context": "werkstatt",
  "api": "OpenAPI_3.0.1",
  "field": [
    {
      "path": "/auftrag/new",
      "operation": "post",
      "input": [],
      "body": {
        "application/json": {
          "type": "Auftraggeber"
        }
      },
      "output": [
        {
          "application/json": {
            "type": "Werkstattauftrag",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "createAuftrag"
    },
    {
      "path": "/auftrag/{auftragsnummer}",
      "operation": "get",
      "input": [
        {
          "name": "auftragsnummer",
          "in": "path",
          "required": true,
          "type": "integer"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "Werkstattauftrag",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "readAuftrag"
    },
    {
      "path": "/auftrag/{auftragsnummer}",
      "operation": "put",
      "input": [
        {
          "name": "auftragsnummer",
          "in": "path",
          "required": true,
          "type": "integer"
        }
      ],
      "body": {
        "application/json": {
          "type": "Auftragsstatus"
        }
      },
      "output": [
        {
          "application/json": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "updateStatus"
    }
  ],
  "server_info": [
    {
      "host": "http://127.0.0.1:9000",
      "environment": "Generated server url"
    }
  ],
  "data_schemas": {
    "Werkstattauftrag": {
      "type": "object",
      "properties": [
        {
          "name": "auftraggeber",
          "type": "#/components/schemas/Auftraggeber"
        },
        {
          "name": "aktuellerBearbeiter",
          "type": "integer"
        },
        {
          "name": "werkstattauftragsnummer",
          "type": "integer"
        },
        {
          "name": "erstellungsdatum",
          "type": "string"
        },
        {
          "name": "zusaetzlicheMaterialien",
          "type": "array"
        },
        {
          "name": "werkstattauftragsstatus",
          "type": "string"
        },
        {
          "name": "auftragspositionen",
          "type": "array"
        },
        {
          "name": "auftraggeberHistorie",
          "type": "array"
        },
        {
          "name": "fahrzeugkennzeichen",
          "type": "string"
        },
        {
          "name": "bearbeiterverlauf",
          "type": "array"
        }
      ]
    },
    "Werkstattservice": {
      "type": "object",
      "properties": [
        {
          "name": "werkstattserviceRef",
          "type": "integer"
        },
        {
          "name": "materialien",
          "type": "array"
        },
        {
          "name": "bezeichnung",
          "type": "string"
        },
        {
          "name": "arbeitswert",
          "type": "#/components/schemas/Arbeitswert"
        }
      ]
    },
    "Auftragsposition": {
      "type": "object",
      "properties": [
        {
          "name": "auftragspositionsnummer",
          "type": "integer"
        },
        {
          "name": "werkstattservice",
          "type": "#/components/schemas/Werkstattservice"
        },
        {
          "name": "menge",
          "type": "number"
        }
      ]
    },
    "Material": {
      "type": "object",
      "properties": [
        {
          "name": "materialnummer",
          "type": "integer"
        },
        {
          "name": "bezeichnung",
          "type": "string"
        },
        {
          "name": "materialpreis",
          "type": "integer"
        },
        {
          "name": "menge",
          "type": "number"
        },
        {
          "name": "status",
          "type": "string"
        }
      ]
    },
    "Auftraggeber": {
      "type": "object",
      "properties": [
        {
          "name": "name",
          "type": "string"
        },
        {
          "name": "typ",
          "type": "string"
        },
        {
          "name": "id",
          "type": "integer"
        }
      ]
    },
    "Auftragsstatus": {
      "type": "object",
      "properties": [
        {
          "name": "status",
          "type": "string"
        }
      ]
    },
    "Arbeitswert": {
      "type": "object",
      "properties": [
        {
          "name": "geldwert",
          "type": "number"
        },
        {
          "name": "waehrung",
          "type": "string"
        },
        {
          "name": "menge",
          "type": "number"
        },
        {
          "name": "zeitwert",
          "type": "number"
        }
      ]
    }
  }
}

=== dqualizer/dqlang/examples/api-schema/api-schema_leasingninja.json
{
  "version": 1,
  "context": "sales",
  "api": "OpenAPI_3.0.1",
  "field": [
    {
      "path": "/riskmanagement/vote",
      "operation": "post",
      "input": [
        {
          "name": "contract_number",
          "in": "query",
          "required": true,
          "type": "string"
        },
        {
          "name": "vote_result",
          "in": "query",
          "required": true,
          "type": "string"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "voteContract"
    },
    {
      "path": "/riskmanagement/rating",
      "operation": "get",
      "input": [
        {
          "name": "contract_number",
          "in": "query",
          "required": true,
          "type": "string"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "showCreditRating"
    },
    {
      "path": "/riskmanagement/contract",
      "operation": "get",
      "input": [
        {
          "name": "number",
          "in": "query",
          "required": true,
          "type": "string"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "showContract"
    },
    {
      "path": "/riskmanagement/rate_contract",
      "operation": "post",
      "input": [
        {
          "name": "contract_number",
          "in": "query",
          "required": true,
          "type": "string"
        },
        {
          "name": "creditRating",
          "in": "query",
          "required": true,
          "type": "integer"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "enterCreditRating"
    },
    {
      "path": "/sales/fillout_contract",
      "operation": "post",
      "input": [
        {
          "name": "contractNumber",
          "in": "query",
          "required": true,
          "type": "string"
        },
        {
          "name": "lessee",
          "in": "query",
          "required": true,
          "type": "string"
        },
        {
          "name": "car",
          "in": "query",
          "required": true,
          "type": "string"
        },
        {
          "name": "price_amount",
          "in": "query",
          "required": true,
          "type": "integer"
        },
        {
          "name": "price_currency",
          "in": "query",
          "required": true,
          "type": "string"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "filloutContract"
    },
    {
      "path": "/sales/sign_contract",
      "operation": "post",
      "input": [
        {
          "name": "contractNumber",
          "in": "query",
          "required": true,
          "type": "string"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "signContract"
    },
    {
      "path": "/sales/view_contract",
      "operation": "get",
      "input": [
        {
          "name": "contractNumber",
          "in": "query",
          "required": false,
          "type": "string"
        }
      ],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "viewContract"
    },
    {
      "path": "/riskmanagement/contracts",
      "operation": "get",
      "input": [],
      "body": {},
      "output": [
        {
          "*/*": {
            "type": "string",
            "expected_code": "200"
          }
        }
      ],
      "operation_id": "listContracts"
    }
  ],
  "server_info": [
    {
      "host": "http://127.0.0.1:8080",
      "environment": "Generated server url"
    }
  ],
  "data_schemas": {}
}
